services:
  mongo1:
    image: mongo
    restart: always
    environment:
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: root
        # MONGO_INITDB_DATABASE: images
    ports:
      - 27017:27017
    volumes:
            - ./db:/docker-entrypoint-initdb.d
            - mongo-data:/data/db
  api:
    build: ./api
    environment:
      HOST_DB_MONGO: mongo1
    depends_on:
      - mongo1
    ports:
      - "5001:5001"
    env_file:
      - ./api/.env

volumes:
  mongo-data: