services:
  mongodb:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: images
    ports:
      - 27017:27017
    volumes:
            - ./db:/docker-entrypoint-initdb.d
            - mongo-data:/data/db
volumes:
  mongo-data: